### ISSUE TITLE
Tratar elementos `NaN`

### ISSUE THREAD

**Issue by nighto** [elmoneto/ruas-e-seus-nomes#4]
Não consegui debugar se veio da API do OSM algum dado inválido (é a primeira vez que uso esse Google Colab), mas rodando com a query "Rio de Janeiro, Rio de Janeiro", no passo `gdf.explore(column="genero", categorical=True, cmap=colors.ListedColormap(['red','blue', 'black']))` ele apresenta este erro:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-21-4e50a8ce0fc6>](https://localhost:8080/#) in <cell line: 1>()
----> 1 gdf.explore(column="genero", categorical=True, cmap=colors.ListedColormap(['red','blue', 'black']))

3 frames
[/usr/local/lib/python3.10/dist-packages/folium/utilities.py](https://localhost:8080/#) in validate_location(location)
     76             )
     77         if math.isnan(float(coord)):
---> 78             raise ValueError("Location values cannot contain NaNs.")
     79     return [float(x) for x in coords]
     80 

ValueError: Location values cannot contain NaNs.
```

**Comment by nighto** [comment]
Bom, talvez ele só não tenha conseguido baixar a lista, pq aparece uma tabela vazia
![image](https://github.com/elmoneto/ruas-e-seus-nomes/assets/397851/b4718ffa-199c-4589-baea-c92a066fe6d4)
Mas o estranho é que o passo anterior aparentemente funcionou
![image](https://github.com/elmoneto/ruas-e-seus-nomes/assets/397851/6d1a91bc-4cad-42c3-bc9b-48ed61bbe14d)

**Comment by elmoneto** [comment]
Oi, @nighto.
O problema da lista vazia foi gerado por um caso atípico dentro dos testes que eu tinha feito. Todas as requisições enviadas ao Overpass concatenam o número '3600' com o ID da relação do município, ou seja, a relação de ID '242397' ([Porto Alegre](https://www.openstreetmap.org/relation/242397)) teria ID na request ao Overpass transformado em '3600242397'. Porém, com o município do Rio de Janeiro essa transformação ocorre de outra forma. Ao invés de '3600', a string 'id:360' é concatenada com o ID original da relação no OpenStreetMap. Então adicionei um método alternativo de request que só é utilizado quando o primeiro método, utilizado até agora, retorna um conjunto de elementos vazio.

Tentei executar a correção no Google Colab e fui desconectado da máquina virtual por conta do método `explore` da biblioteca geopandas utilizar muitos recursos de CPU e memória, já que ela tenta renderizar milhares de geometrias dentro de uma instância de mapa no navegador. Localmente, no meu próprio ambiente com Jupyter Notebook, consegui executar sem problemas. Abaixo, a captura de tela do resultado do método `explore` sobre os dados do município do Rio de Janeiro. 
![Captura de tela de 2024-02-02 10-46-43](https://github.com/elmoneto/ruas-e-seus-nomes/assets/6998315/5f8668c1-3946-4663-9666-4315de6d056d)

**Comment by nighto** [comment]
Obrigado! :)
